version: "3.9"

services:
  wedding-app:
    image: wedding-planner:6.0
    container_name: wedding_app
    ports:
      - "8501:8501"   # Streamlit UI
    volumes:
      - .:/app       
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    depends_on:
      - qdrant

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_db
    ports:
      - "6333:6333"   # Qdrant
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped

volumes:
  qdrant_data:




# FROM python:3.10
 
# # Step 2: Set the working director inside the container
# WORKDIR /app

# # Copy application code into the container
# COPY requirements.txt /app/
# RUN pip install --upgrade pip
# RUN pip install --no-cache-dir -r requirements.txt

# # Copy project files
# COPY . /app

# # Step 5: Expose the application port
# EXPOSE 8501
 
# # Run the Streamlit app using -m pattern
# CMD ["streamlit", "run", "app.py"]
